### ISSUE TITLE
Unable to connect to the testnet

### ISSUE THREAD

**Issue by Guppster** [ArkEcosystem/ark-client#1]
I attempted to run `connect testnet` but received a connection refused. 

```
ark> connect testnet
Can't get peers from network: Error: connect ECONNREFUSED 5.39.9.249:4000
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at Request._callback (/usr/lib/node_modules/ark-client/index.js:329:56)
    at self.callback (/usr/lib/node_modules/ark-client/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/lib/node_modules/ark-client/node_modules/request/request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
```

`connect mainnet` works correctly

**Comment by fix** [comment]
yo i should update, seedpeers have changed

**Comment by fix** [comment]
should be fixed in last version. testnet is now devnet. Can you check this out?

**Comment by Guppster** [comment]
Devnet works now but now when an improper value is specified after the connect keyword the error isnt handled correctly. 

```
ark> connect masternet
readline.js:973
            throw err;
            ^

TypeError: Cannot read property 'peers' of undefined
    at CommandInstance.<anonymous> (/usr/lib/node_modules/ark-client/index.js:272:21)
    at EventEmitter.session.execCommandSet (/usr/lib/node_modules/ark-client/node_modules/vorpal/dist/session.js:470:20)
    at EventEmitter.vorpal._exec (/usr/lib/node_modules/ark-client/node_modules/vorpal/dist/vorpal.js:960:18)
    at EventEmitter.vorpal._execQueueItem (/usr/lib/node_modules/ark-client/node_modules/vorpal/dist/vorpal.js:751:17)
    at EventEmitter.vorpal._queueHandler (/usr/lib/node_modules/ark-client/node_modules/vorpal/dist/vorpal.js:735:10)
    at EventEmitter.vorpal.exec (/usr/lib/node_modules/ark-client/node_modules/vorpal/dist/vorpal.js:682:10)
    at /usr/lib/node_modules/ark-client/node_modules/vorpal/dist/vorpal.js:625:10
    at .completed (/usr/lib/node_modules/ark-client/node_modules/vorpal/dist/ui.js:220:13)
    at PromptUI.onCompletion (/usr/lib/node_modules/ark-client/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/lib/node_modules/ark-client/node_modules/rx-lite/rx.lite.js:1550:12)
```
