### ISSUE TITLE
Some ledger stuff does not work anymore

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/ark-client#21]
PS F:\> ark-client
C:\Users\Jarunik\AppData\Roaming\npm\node_modules\ark-client\index.js:222
async function populateLedgerAccounts() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

**Comment by alexbarnsley** [comment]
Interesting. Is async on the node_modules folder? Looks like no code has changed since 7th October. What node and npm version are you using? Could try another `npm install`

**Comment by Jarunik** [comment]
Oh well. Never mind. Might be just me.

**Comment by alexbarnsley** [comment]
Was it something I said @Jarunik? 😱 Was trying to help 😞

**Comment by boldninja** [comment]
@alexbarnsley why you no help! 😞

**Comment by Jarunik** [comment]
i updated npm and nodejs and installed it again ... so now i have the same errors like in the still open issue. 

See: https://github.com/ArkEcosystem/ark-client/issues/17#issuecomment-343661004

**Comment by alexbarnsley** [comment]
Trying @boldninja 😞 

Thanks @Jarunik I'll take a look at that issue later on today
