### ISSUE TITLE
Trouble with installing & running ark-client

### ISSUE THREAD

**Issue by mirzap** [ArkEcosystem/ark-client#28]
I tried with a few Node versions: 8.9.4, 8.7.x, 7.6.x (Ubuntu 16.04) but always I get bunch of errors, or in this case when I finally got message that package is installed and binary linked:

```
titan@ark:~$ ark-client
/home/titan/.nvm/versions/node/v8.9.4/lib/node_modules/ledgerco/src/utils.js:19
type Defer<T> = {
     ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/titan/.nvm/versions/node/v8.9.4/lib/node_modules/ark-client/src/LedgerArk.js:4:13)
```

any advice?

**Comment by alexbarnsley** [comment]
I will be able to take a look in the morning (UK time). Someone else has reported this on Slack today so it's already top of my list. I'll let you know what I find. Interestingly you're both on Ubuntu 16

**Comment by alexbarnsley** [comment]
@mirzap i've done a PR which fixes it I think (did for me on Ubuntu - i could replicate your issue). If you could check the description of the PR to test, that would be great! PR: #29 

For reference: Possible duplicate of #27

**Comment by mirzap** [comment]
PR #29 fixes the issue.
